export const projectsData = [
  {
    id: 1,
    title: "App Background remover",
    name: "Background",
    subname: "Remover",
    image: "/images/Background-remover.png",
    github: "https://github.com/tonpseudo/projet2",
    website: "/bg-remover",
    stacks: [
      "React",
      "Vite",
      "Axios",
      "CSS",
      "FontAwesome",
      "Node.js",
      "Express.js",
      "Nodemon",
      "Python",
      "FastAPI",
      "Rembg",
      "Uvicorn",
    ],
  },
  {
    id: 2,
    title: "App Text To Speech",
    name: "Voxora",
    subname: "Lab",
    image: "/images/Voxora.png",
    github: "https://github.com/MaelleVo/TTS-project",
    website: "/tts",
    stacks: [
      "Python",
      "React",
      "Javacsript",
      "FastAPI",
      "MongoDB",
      "Docker",
      "AWS",
      "TTS",
      "Kororo",
      "Coqui AI",
      "Vercel",
    ],
  },
  {
    id: 3,
    title: "App Text To Speech",
    name: "Voxora",
    subname: "Lab",
    image: "/images/venir.png",
    github: "https://github.com/MaelleVo/TTS-project",
    website: "/tts",
    stacks: [
      "Python",
      "React",
      "Javacsript",
      "FastAPI",
      "MongoDB",
      "Docker",
      "AWS",
      "TTS",
      "Kororo",
      "Coqui AI",
      "Vercel",
    ],
  },
];
